----------------------------------------------------------------------------------------------------
 2016-11-12 16:00:51,208 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:01:00,802 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:02:02,543 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:02:10,299 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:02:38,595 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:41:37,436 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:43:36,873 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:43:38,797 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:43:53,776 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:44:17,609 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:44:19,444 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:56:06,797 ERROR - in register_routes [__init__.py:55]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 16:56:44,194 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 16:58:58,238 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 16:59:13,479 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:02:36,979 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:02:39,173 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:03:02,515 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:03:14,764 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:04:41,506 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:06:14,285 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:06:14,286 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:14:05,745 DEBUG - in about [home_controller.py:17]:
 about.....
----------------------------------------------------------------------------------------------------
 2016-11-12 17:14:28,354 DEBUG - in home [home_controller.py:11]:
 index.....
----------------------------------------------------------------------------------------------------
 2016-11-12 17:14:30,478 DEBUG - in about [home_controller.py:17]:
 about.....
----------------------------------------------------------------------------------------------------
 2016-11-12 17:14:31,686 DEBUG - in home [home_controller.py:11]:
 index.....
----------------------------------------------------------------------------------------------------
 2016-11-12 17:14:32,721 DEBUG - in contact [home_controller.py:23]:
 contact.....
----------------------------------------------------------------------------------------------------
 2016-11-12 17:14:52,301 DEBUG - in contact [home_controller.py:23]:
 contact.....
----------------------------------------------------------------------------------------------------
 2016-11-12 19:10:54,824 ERROR - in register_routes [__init__.py:55]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-13 05:38:26,832 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:43:00,003 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:43:57,504 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:44:16,312 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:50:46,780 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:52:43,408 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 06:05:03,954 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 11:56:16,348 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 11:56:35,426 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 12:05:32,346 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x10e3f45d0>
----------------------------------------------------------------------------------------------------
 2016-11-13 12:05:32,346 INFO - in update [user_api_controller.py:60]:
 582798778d299c6852b07776
----------------------------------------------------------------------------------------------------
 2016-11-13 12:06:30,893 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x1104af5d0>
----------------------------------------------------------------------------------------------------
 2016-11-13 12:06:30,893 INFO - in update [user_api_controller.py:60]:
 582798778d299c6852b07776
----------------------------------------------------------------------------------------------------
 2016-11-13 12:07:44,014 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x101807a50>
----------------------------------------------------------------------------------------------------
 2016-11-13 12:07:44,015 INFO - in update [user_api_controller.py:60]:
 582798778d299c6852b07776
----------------------------------------------------------------------------------------------------
 2016-11-14 13:34:05,499 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-14 13:34:10,252 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-14 13:37:12,956 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x1073fbe90>
----------------------------------------------------------------------------------------------------
 2016-11-14 13:37:12,956 INFO - in update [user_api_controller.py:60]:
 582793248d299c67a0c8fccf
----------------------------------------------------------------------------------------------------
 2016-11-15 01:23:43,848 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x104956a50>
----------------------------------------------------------------------------------------------------
 2016-11-15 01:23:43,848 INFO - in update [user_api_controller.py:60]:
 582793248d299c67a0c8fccf
----------------------------------------------------------------------------------------------------
 2016-11-15 01:23:57,579 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x104956a50>
----------------------------------------------------------------------------------------------------
 2016-11-15 01:23:57,580 INFO - in update [user_api_controller.py:60]:
 5827da808d299c6852b07779
----------------------------------------------------------------------------------------------------
 2016-11-15 10:34:34,164 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x10f05a710>
----------------------------------------------------------------------------------------------------
 2016-11-15 10:34:34,164 INFO - in update [user_api_controller.py:60]:
 582a742e8d299c15f2aee826
----------------------------------------------------------------------------------------------------
 2016-11-15 12:22:58,827 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x10f08b0d0>
----------------------------------------------------------------------------------------------------
 2016-11-15 12:22:58,827 INFO - in update [user_api_controller.py:60]:
 5827da058d299c6852b07778
----------------------------------------------------------------------------------------------------
 2016-11-15 12:23:11,634 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x10f05ad10>
----------------------------------------------------------------------------------------------------
 2016-11-15 12:23:11,634 INFO - in update [user_api_controller.py:60]:
 5827da058d299c6852b07778
----------------------------------------------------------------------------------------------------
 2016-11-15 14:27:05,067 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-15 14:28:39,201 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x107b4ad90>
----------------------------------------------------------------------------------------------------
 2016-11-15 14:28:39,201 INFO - in update [user_api_controller.py:60]:
 5827da058d299c6852b07778
----------------------------------------------------------------------------------------------------
 2016-11-15 15:51:15,499 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x107b4a2d0>
----------------------------------------------------------------------------------------------------
 2016-11-15 15:51:15,499 INFO - in update [user_api_controller.py:60]:
 5827da058d299c6852b07778
----------------------------------------------------------------------------------------------------
 2016-11-15 15:51:25,971 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x107b64a90>
----------------------------------------------------------------------------------------------------
 2016-11-15 15:51:25,971 INFO - in update [user_api_controller.py:60]:
 5827da058d299c6852b07778
----------------------------------------------------------------------------------------------------
 2016-11-15 15:51:27,716 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-15 15:52:19,737 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x107b4a310>
----------------------------------------------------------------------------------------------------
 2016-11-15 15:52:19,737 INFO - in update [user_api_controller.py:60]:
 582798898d299c6852b07777
----------------------------------------------------------------------------------------------------
 2016-11-15 21:21:27,253 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-16 01:33:16,240 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-16 01:45:52,582 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-16 01:46:30,728 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-16 18:30:07,008 INFO - in update [user_api_controller.py:59]:
 <website.models.user.User object at 0x101fb9610>
----------------------------------------------------------------------------------------------------
 2016-11-16 18:30:07,008 INFO - in update [user_api_controller.py:60]:
 582abfd68d299c3637a68967
----------------------------------------------------------------------------------------------------
 2016-11-17 01:50:13,089 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-20 13:00:31,822 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-20 14:59:50,856 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:42,875 ERROR - in error_404 [__init__.py:64]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:42,880 ERROR - in error_404 [__init__.py:64]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:43,129 ERROR - in error_404 [__init__.py:64]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:43,166 ERROR - in error_404 [__init__.py:64]:
 404
